skydrop/src/drivers/bluetooth/pan1026.cpp
use function memset in “string.h” to set array bt_link_key‘s all value to zero
=> use memset to set zero

skydrop/src/fc/protocols/LK8EX1.cpp, skydrop/src/fc/protocols/digifly.cpp
The line ending for all NMEA protocols has to be <cr><lf> and not <lf> only as currently implemented.
=> Digifly and LK8EX1 protocols do not fulfill NMEA standard

skydrop/src/debug.cpp, skydrop/src/debug.h
.text + .data + .bootloader: 89.0% -> 84.6%
Addtionally ensure, that message string is not longer than buffer (vsnprintf).
=> "DEBUG" is now a macro calling "debug", so saving some progmem:

skydrop/src/common.cpp, skydrop/src/common.h, skydrop/src/fc/fc.cpp, skydrop/src/fc/logger/igc.cpp, skydrop/src/fc/logger/logger.cpp, skydrop/src/fc/logger/logger.h, skydrop/src/gui/gui.cpp, skydrop/src/gui/gui.h, skydrop/src/gui/gui_list.cpp, skydrop/src/gui/gui_list.h, skydrop/src/gui/settings/gui_flightlog1.cpp, skydrop/src/gui/settings/gui_flightlog1.h, skydrop/src/gui/settings/gui_flightlog2.cpp, skydrop/src/gui/settings/gui_flightlog2.h, skydrop/src/gui/settings/gui_flightlog3.cpp, skydrop/src/gui/settings/gui_flightlog3.h, skydrop/src/gui/settings/set_logger.cpp, skydrop/src/gui/settings/settings.cpp, updates/changelog.txt
Added a "Flight log" in the settings menu to select
a previous log file and see the flight statistics again.
This is used as an extension point to store even more
valuable data inside the log file and present it to
the pilot after the flight.
Fixes the following requests:
#208
#73
=> Store flight statistics in log file and offer file explorer for flight statistics, v2

skydrop/src/common.cpp, skydrop/src/drivers/sensors/gps_l80.cpp
This driver offers the functionality to simulate GPS data read from a file instead of the sensor. This allows
various flight simulations and checking, that the widgets (or other
code) behaves as expected.
To use that feature define the preprocessor constant GPS_SIMULATION
and re-compile the code. Then place a GPS file onto the SD card as
"GPS-SIM.TXT" which contains the GPS data. This file can be generated
in two different ways:
1. Use SkyDrop and turn on "debug log" and "gps debug", record some
movements and rename "DEBUG.LOG" into "GPS-SIM.TXT"
2. Convert an existing IGC file into GPS, e.g.
gpsbabel -i igc -f existing-flight.igc
-x track,speed,course,fix=2d
-o nmea -F GPS-SIM.TXT
=> GPS simulation as a compile time option.

skydrop/utils/ee_maper/CParser.py
in verbose mode. The parser is unable to deal with some
language constructs (e.g. function pointers) and throws an
exception in this case. These are now only printed if verbose is on.
This is nothing new for the parser at it is already done
for some other things. My change extends them for SkyDrops
language constructs, so that we can use the mapper without
seeing many (unnecessary) exceptions cluttering the output.
By turning on verbose, they will still be shown.
=> CParser modified, so that various exceptions are only printed

skydrop_configurator/app/res/desc.json
When loading a CFG.EE that used a compass heading points widget the GUI showed "Unknown" because of a name inconsistency in the json description file:
=> configurator: fixed compass heading points widget

skydrop/src/fc/conf.h, skydrop/src/gui/pages.cpp, skydrop/src/gui/pages.h, skydrop/src/gui/settings/set_display.cpp
To use this, turn on Menu>Settings>Display>Cycle.
Fixes https://github.com/fhorinek/SkyDrop/issues/328
=> Functionality to automatically cycle between the screens.

skydrop/src/fc/agl.cpp
vario is already very well calibrated, when skydrop is turned on.
Then no calibration will be made, because height_delta < 10. So still,
the vario value will be associated with the (bad) error of 100 and will
only be corrected to a even worse GPS height, if the GPS height is so worse
that it is more than 10m away from vario. This use case is now fixed.
=> Fix auto calibration for a already well adjusted vario value:

skydrop/src/gui/gui.cpp
A new CPP definition SHOW_FPS is introduced to
enable/disable code to show frames per second,
instead of the previous used "commenting out".
This also reduces RAM usage (6 byte) as the needed
variables are also #ifdef'ed.
=> Reduce RAM usage of fps drawing

skydrop/src/fc/fc.cpp, skydrop/src/fc/fc.h, skydrop/src/gui/settings/gui_flightdetail.cpp, updates/changelog.txt
The odometer at the beginning of the flight is saved and used to
compute the distance travelled on the flight after the landing.
This data is stored in the log file and shown in the flight log
after selecting a log file during file_details.
This fixes https://github.com/fhorinek/SkyDrop/issues/357
It increases the following sizes:
gcc version 7.2.0 (Fedora 7.2.0-1.fc28)
Mem     size-before     size-after      delta    limit
Flash   186514          186784          +270    196608
RAM      11922           11930            +8     13107
EEPROM     773             773             0      2048
=> Count, store and show distance of a flight (odometer).

.gitattributes
Whenver two branches change the changelog.txt we get a git conflict.
By changing the merge driver to "union" we will not get a conflict.
Instead the driver merges the union of all changes into the file.
more info at http://krlmlr.github.io/using-gitattributes-to-avoid-merge-conflicts/
=> Change merge driver for changelog.txt to avoid conflicts

skydrop/utils/airspace/spoof.py, skydrop/utils/airspace/visualize.py
Allow visualize.py to work without /dev/ttyUSB1 button for selecting a point, as this keeps the existing zoom function.
=> Fix for missing /dev/ttyUSB1

skydrop/src/drivers/lcd_disp.cpp, skydrop/src/drivers/lcd_disp.h
disp.sin_table is changed to a more compact form, using uint8_t instead
of float to store the values. Additionally it is moved from RAM to PROGMEM
to further save memory.
gcc version 7.2.0 (Fedora 7.2.0-1.fc28)
Mem     size-before     size-after      delta    limit
Flash   187342          187290           -52    196608
RAM      10710           10346          -364     13107
EEPROM     773             773             0      2048
By using uint8_t instead of float introduces a maximum error
of 0.003802. As "get_sin" is only used to draw pixels on screen,
this minor error is not important.
=> Reduce memory for sin_table and move to PROGMEM

skydrop/src/drivers/sensors/gps_l80.cpp
Previously the GPS_SIMULATION needed data from UART to get a correct
timing behaviour. However, the read data is dropped in favour of
GPS-SIMULATION data. This does not work with the borked SkyDrop
without connecting the GPS-USART.
This fix allows GPS-SIMULATION to work without a USB connection.
Timing is taken from NMEA sentence "RMC" which is scheduled every second.
=> Improved GPS_SIMULATION to work with "borked" SkyDrop

skydrop/.cproject, skydrop/src/drivers/battery.cpp, skydrop/src/drivers/battery.h, skydrop/src/fc/conf.cpp, skydrop/src/fc/conf.h, skydrop/src/gui/gui.cpp, skydrop/src/gui/settings/set_calib.cpp, skydrop/utils/calib/bat-cal-to-csv.py
New menu item "Settings>Advanced>Calibration>Battery". Choosing this will
start a calibration. The user has to fully charge the battery, and then
remove power, so that the battery will be discharged completely. During
discharge, the current ADC value will be saved periodically. After turning
on power, this file will be converted to a more compact form (averaging
the values for 0-100%) and then used during normal operation.
This results in a much better percentage and therefore allows the user
to better know how long the device lasts.
Fixes https://github.com/fhorinek/SkyDrop/issues/340
=> Add code for battery calibration.

skydrop/src/fc/fc.cpp, updates/changelog.txt
inside a comment every 5 minutes (like battery level)
=> Flight log files (e.g. IGC) now contain temperature

skydrop/src/fc/navigation.cpp
The value of calc_speed was wrongly divided by 100 (because we previously used cm instead of m).
The use of "abs()" instead of "fabs()" introduced a great numerical error.
These bugs lead to odometer not working correctly.
=> Fix wrong odometer computation

skydrop/src/gui/widgets/airspace.cpp, skydrop/src/gui/widgets/navigation.cpp, skydrop/src/gui/widgets/widgets.cpp, skydrop/src/gui/widgets/widgets.h
If distance is ^GPS_DIST_UNIT_I and distance <1km, then there are two bugs:
1. Widget "airspace" shows "100km" for 100m, which is obviously wrong.
Additionally "m" is appended to 100.
2. Widget "odo" shows a unit, e.g. "100m" and no unit if > 1km
This patch fixes both bugs and saves some PROGMEM.
=> Fix distance display

skydrop/utils/build/post_build.sh
Currently post_build.sh needs a special avr-size command
that is able to handle "--format=avr". This commit
gives more flexibility by using "--format=sysv" which is
available in all versions of avr-size.
Fixes https://github.com/fhorinek/SkyDrop/issues/439
=> Fix post_build.sh to work with any "avr-size" command

skydrop/src/fc/airspace.cpp, skydrop/src/fc/fc.cpp, skydrop/src/fc/fc.h, skydrop/src/fc/navigation.cpp, skydrop/src/fc/waypoint.cpp, skydrop/src/gui/widgets/navigation.cpp
This is important for odometer, especially when hiking.
As we compute the distance every second, we get a huge
error if we have accuracy of 1 meter instead of centimeter:
For a given flight, the previous implementation lead to
17.7km and with increased accuracy to 18.7km. This is an
error of 6%.
For hiking the error is much greater, because we only walk around 1m per second. So if we walk 1.5m per second, the error is 50%.
=> Increase accuracy of gps_distance from meter to cm.
